// commitlint.config.cjs
// Conventional Commits enforcement for APEX OmniHub.
//
// IGNORE STRATEGY: Only validate commits whose first line already attempts the
// conventional format (`type(scope): subject` or `type: subject`).  Any commit
// that does not open with a lowercase type token is silently skipped — this
// covers GitHub-UI auto-commits ("Add files via upload", "Delete …", "Rename …",
// "Update …", "Create …"), squash-merge PR titles without a type prefix
// ("Format Python code with Black …"), emoji-prefixed commits, and merge commits.
// This makes the gate forward-looking: new work that deliberately follows the
// convention is validated; historical / UI-generated messages are not penalised.

module.exports = {
  extends: ['@commitlint/config-conventional'],

  ignores: [
    // ── primary gate: skip anything that doesn't open with a conventional type ──
    // A conventional commit header starts with:  type(scope)!?: <subject>
    // where type is all lowercase ASCII letters.
    // If the first line of the raw commit message doesn't match this shape,
    // skip validation entirely — no false positives from legacy / UI commits.
    (commit) =>
      !/^[a-z]+(\([\w/-]+\))?!?:\s+\S/.test(commit.split('\n')[0]),

    // ── belt-and-suspenders: explicit patterns that must always be ignored ──
    // Merge commits (GitHub auto-generated)
    (commit) => /^Merge /i.test(commit.split('\n')[0]),
    // Revert commits generated by GitHub
    (commit) => /^Revert "/i.test(commit.split('\n')[0]),
  ],

  rules: {
    // Downgrade length rules from error → warn so that verbose sprint commit
    // bodies and Claude session URL footers never block CI.
    'header-max-length': [1, 'warn', 150],
    'subject-max-length': [1, 'warn', 150],
    'footer-max-line-length': [1, 'warn', 300],
    'body-max-line-length': [1, 'warn', 300],

    // sentence-case subjects are common in squash-merge PR titles — warn only.
    'subject-case': [1, 'warn', 'never', ['pascal-case', 'upper-case']],
  },
};
