// Comprehensive mock for lucide-react to satisfy registry and component imports in tests
// This file is automatically picked up by Vitest when vi.mock('lucide-react') is called.

import React from 'react';

const MockIcon = ({ name, ...props }: { name: string; [key: string]: any }) =>
  React.createElement('svg', {
    'data-testid': `icon-${name}`,
    ...props
  });

export const Activity = (props: any) => React.createElement(MockIcon, { name: 'Activity', ...props });
export const AlertCircle = (props: any) => React.createElement(MockIcon, { name: 'AlertCircle', ...props });
export const AlertTriangle = (props: any) => React.createElement(MockIcon, { name: 'AlertTriangle', ...props });
export const ArrowLeft = (props: any) => React.createElement(MockIcon, { name: 'ArrowLeft', ...props });
export const ArrowRight = (props: any) => React.createElement(MockIcon, { name: 'ArrowRight', ...props });
export const BarChart3 = (props: any) => React.createElement(MockIcon, { name: 'BarChart3', ...props });
export const Bell = (props: any) => React.createElement(MockIcon, { name: 'Bell', ...props });
export const Bot = (props: any) => React.createElement(MockIcon, { name: 'Bot', ...props });
export const Building2 = (props: any) => React.createElement(MockIcon, { name: 'Building2', ...props });
export const Calendar = (props: any) => React.createElement(MockIcon, { name: 'Calendar', ...props });
export const Check = (props: any) => React.createElement(MockIcon, { name: 'Check', ...props });
export const CheckCircle = (props: any) => React.createElement(MockIcon, { name: 'CheckCircle', ...props });
export const CheckCircle2 = (props: any) => React.createElement(MockIcon, { name: 'CheckCircle2', ...props });
export const CheckSquare = (props: any) => React.createElement(MockIcon, { name: 'CheckSquare', ...props });
export const ChevronDown = (props: any) => React.createElement(MockIcon, { name: 'ChevronDown', ...props });
export const ChevronRight = (props: any) => React.createElement(MockIcon, { name: 'ChevronRight', ...props });
export const Code = (props: any) => React.createElement(MockIcon, { name: 'Code', ...props });
export const Copy = (props: any) => React.createElement(MockIcon, { name: 'Copy', ...props });
export const Cpu = (props: any) => React.createElement(MockIcon, { name: 'Cpu', ...props });
export const Crown = (props: any) => React.createElement(MockIcon, { name: 'Crown', ...props });
export const Database = (props: any) => React.createElement(MockIcon, { name: 'Database', ...props });
export const Download = (props: any) => React.createElement(MockIcon, { name: 'Download', ...props });
export const Edit = (props: any) => React.createElement(MockIcon, { name: 'Edit', ...props });
export const ExternalLink = (props: any) => React.createElement(MockIcon, { name: 'ExternalLink', ...props });
export const Eye = (props: any) => React.createElement(MockIcon, { name: 'Eye', ...props });
export const Facebook = (props: any) => React.createElement(MockIcon, { name: 'Facebook', ...props });
export const FileText = (props: any) => React.createElement(MockIcon, { name: 'FileText', ...props });
export const Fingerprint = (props: any) => React.createElement(MockIcon, { name: 'Fingerprint', ...props });
export const Folder = (props: any) => React.createElement(MockIcon, { name: 'Folder', ...props });
export const GitBranch = (props: any) => React.createElement(MockIcon, { name: 'GitBranch', ...props });
export const Globe = (props: any) => React.createElement(MockIcon, { name: 'Globe', ...props });
export const Headphones = (props: any) => React.createElement(MockIcon, { name: 'Headphones', ...props });
export const Heart = (props: any) => React.createElement(MockIcon, { name: 'Heart', ...props });
export const Home = (props: any) => React.createElement(MockIcon, { name: 'Home', ...props });
export const Image = (props: any) => React.createElement(MockIcon, { name: 'Image', ...props });
export const Info = (props: any) => React.createElement(MockIcon, { name: 'Info', ...props });
export const Instagram = (props: any) => React.createElement(MockIcon, { name: 'Instagram', ...props });
export const Key = (props: any) => React.createElement(MockIcon, { name: 'Key', ...props });
export const Layers = (props: any) => React.createElement(MockIcon, { name: 'Layers', ...props });
export const LayoutDashboard = (props: any) => React.createElement(MockIcon, { name: 'LayoutDashboard', ...props });
export const LifeBuoy = (props: any) => React.createElement(MockIcon, { name: 'LifeBuoy', ...props });
export const Link = (props: any) => React.createElement(MockIcon, { name: 'Link', ...props });
export const Link2 = (props: any) => React.createElement(MockIcon, { name: 'Link2', ...props });
export const ListChecks = (props: any) => React.createElement(MockIcon, { name: 'ListChecks', ...props });
export const Loader2 = (props: any) => React.createElement(MockIcon, { name: 'Loader2', ...props });
export const Lock = (props: any) => React.createElement(MockIcon, { name: 'Lock', ...props });
export const LogOut = (props: any) => React.createElement(MockIcon, { name: 'LogOut', ...props });
export const Mail = (props: any) => React.createElement(MockIcon, { name: 'Mail', ...props });
export const MessageCircle = (props: any) => React.createElement(MockIcon, { name: 'MessageCircle', ...props });
export const MessageSquare = (props: any) => React.createElement(MockIcon, { name: 'MessageSquare', ...props });
export const Mic = (props: any) => React.createElement(MockIcon, { name: 'Mic', ...props });
export const MicOff = (props: any) => React.createElement(MockIcon, { name: 'MicOff', ...props });
export const Monitor = (props: any) => React.createElement(MockIcon, { name: 'Monitor', ...props });
export const Moon = (props: any) => React.createElement(MockIcon, { name: 'Moon', ...props });
export const Music = (props: any) => React.createElement(MockIcon, { name: 'Music', ...props });
export const Network = (props: any) => React.createElement(MockIcon, { name: 'Network', ...props });
export const Pause = (props: any) => React.createElement(MockIcon, { name: 'Pause', ...props });
export const Play = (props: any) => React.createElement(MockIcon, { name: 'Play', ...props });
export const PlayCircle = (props: any) => React.createElement(MockIcon, { name: 'PlayCircle', ...props });
export const Plug = (props: any) => React.createElement(MockIcon, { name: 'Plug', ...props });
export const Plus = (props: any) => React.createElement(MockIcon, { name: 'Plus', ...props });
export const RefreshCw = (props: any) => React.createElement(MockIcon, { name: 'RefreshCw', ...props });
export const RotateCcw = (props: any) => React.createElement(MockIcon, { name: 'RotateCcw', ...props });
export const Save = (props: any) => React.createElement(MockIcon, { name: 'Save', ...props });
export const Search = (props: any) => React.createElement(MockIcon, { name: 'Search', ...props });
export const Server = (props: any) => React.createElement(MockIcon, { name: 'Server', ...props });
export const Settings = (props: any) => React.createElement(MockIcon, { name: 'Settings', ...props });
export const Shield = (props: any) => React.createElement(MockIcon, { name: 'Shield', ...props });
export const ShieldCheck = (props: any) => React.createElement(MockIcon, { name: 'ShieldCheck', ...props });
export const ShieldOff = (props: any) => React.createElement(MockIcon, { name: 'ShieldOff', ...props });
export const SkipBack = (props: any) => React.createElement(MockIcon, { name: 'SkipBack', ...props });
export const SkipForward = (props: any) => React.createElement(MockIcon, { name: 'SkipForward', ...props });
export const Smartphone = (props: any) => React.createElement(MockIcon, { name: 'Smartphone', ...props });
export const Sparkles = (props: any) => React.createElement(MockIcon, { name: 'Sparkles', ...props });
export const Sun = (props: any) => React.createElement(MockIcon, { name: 'Sun', ...props });
export const Target = (props: any) => React.createElement(MockIcon, { name: 'Target', ...props });
export const Trash2 = (props: any) => React.createElement(MockIcon, { name: 'Trash2', ...props });
export const TrendingUp = (props: any) => React.createElement(MockIcon, { name: 'TrendingUp', ...props });
export const Unlink = (props: any) => React.createElement(MockIcon, { name: 'Unlink', ...props });
export const Unlock = (props: any) => React.createElement(MockIcon, { name: 'Unlock', ...props });
export const User = (props: any) => React.createElement(MockIcon, { name: 'User', ...props });
export const Wallet = (props: any) => React.createElement(MockIcon, { name: 'Wallet', ...props });
export const Workflow = (props: any) => React.createElement(MockIcon, { name: 'Workflow', ...props });
export const Wrench = (props: any) => React.createElement(MockIcon, { name: 'Wrench', ...props });
export const X = (props: any) => React.createElement(MockIcon, { name: 'X', ...props });
export const XCircle = (props: any) => React.createElement(MockIcon, { name: 'XCircle', ...props });
export const Youtube = (props: any) => React.createElement(MockIcon, { name: 'Youtube', ...props });
export const Zap = (props: any) => React.createElement(MockIcon, { name: 'Zap', ...props });
