import { z } from 'zod';

const appRegistryEntrySchema = z.object({
  key: z.string().min(1),
  label: z.string().min(1),
  routePath: z.string().startsWith('/omnidash'),
  category: z.enum(['control-plane', 'security', 'automation', 'operations', 'platform']),
  iconAssetKey: z.string().min(1),
  logoDomain: z.string().min(1),
  chaosTarget: z.boolean(),
  comingSoon: z.boolean(),
  healthContext: z.object({
    health: z.enum(['green', 'yellow', 'red']),
    insight: z.string().min(1),
  }),
  dashboard: z.object({
    syncedMinutesAgo: z.number().int().nonnegative(),
    status: z.enum(['Live', 'Partial']),
  }),
});

export type AppRegistryEntry = z.infer<typeof appRegistryEntrySchema>;

const appRegistrySource = [
  {
    key: 'omniboard',
    label: 'OmniBoard',
    routePath: '/omnidash',
    category: 'control-plane',
    iconAssetKey: 'omniboard',
    logoDomain: 'apexomnihub.icu',
    chaosTarget: false,
    comingSoon: false,
    healthContext: { health: 'green', insight: 'Control plane telemetry healthy and within SLO.' },
    dashboard: { syncedMinutesAgo: 1, status: 'Live' },
  },
  {
    key: 'omniport',
    label: 'OmniPort',
    routePath: '/omnidash/omniport',
    category: 'platform',
    iconAssetKey: 'links',
    logoDomain: 'cloudflare.com',
    chaosTarget: true,
    comingSoon: false,
    healthContext: { health: 'yellow', insight: 'Throughput elevated; queue depth remains controlled.' },
    dashboard: { syncedMinutesAgo: 2, status: 'Live' },
  },
  {
    key: 'maestro',
    label: 'Maestro',
    routePath: '/omnidash/maestro',
    category: 'automation',
    iconAssetKey: 'automations',
    logoDomain: 'temporal.io',
    chaosTarget: true,
    comingSoon: false,
    healthContext: { health: 'green', insight: 'Workflow orchestration heartbeat stable across shards.' },
    dashboard: { syncedMinutesAgo: 1, status: 'Live' },
  },
  {
    key: 'fortress',
    label: 'Fortress',
    routePath: '/omnidash/fortress',
    category: 'security',
    iconAssetKey: 'audits',
    logoDomain: 'supabase.com',
    chaosTarget: true,
    comingSoon: false,
    healthContext: { health: 'green', insight: 'Zero-trust controls passing policy and audit checks.' },
    dashboard: { syncedMinutesAgo: 1, status: 'Live' },
  },
  {
    key: 'orchestrator',
    label: 'Orchestrator',
    routePath: '/omnidash/orchestrator',
    category: 'control-plane',
    iconAssetKey: 'workflows',
    logoDomain: 'python.org',
    chaosTarget: true,
    comingSoon: false,
    healthContext: { health: 'yellow', insight: 'Planner latency elevated during simulation windows.' },
    dashboard: { syncedMinutesAgo: 3, status: 'Partial' },
  },
  {
    key: 'omniskills',
    label: 'OmniSkills',
    routePath: '/omnidash/omniskills',
    category: 'platform',
    iconAssetKey: 'omniskills',
    logoDomain: 'openai.com',
    chaosTarget: false,
    comingSoon: true,
    healthContext: { health: 'green', insight: 'Skill bundle indexing remains up-to-date.' },
    dashboard: { syncedMinutesAgo: 4, status: 'Live' },
  },
  {
    key: 'physiomni',
    label: 'PhysiOmni',
    routePath: '/omnidash/physiomni',
    category: 'operations',
    iconAssetKey: 'physiomni',
    logoDomain: 'whoop.com',
    chaosTarget: false,
    comingSoon: true,
    healthContext: { health: 'green', insight: 'Device ingest channels reporting nominal cadence.' },
    dashboard: { syncedMinutesAgo: 5, status: 'Live' },
  },
  {
    key: 'audits',
    label: 'Audits',
    routePath: '/omnidash/audits',
    category: 'security',
    iconAssetKey: 'audits',
    logoDomain: 'vercel.com',
    chaosTarget: true,
    comingSoon: true,
    healthContext: { health: 'green', insight: 'Audit event writes are durable and replayable.' },
    dashboard: { syncedMinutesAgo: 2, status: 'Live' },
  },
  {
    key: 'links',
    label: 'Links',
    routePath: '/omnidash/links',
    category: 'platform',
    iconAssetKey: 'links',
    logoDomain: 'zapier.com',
    chaosTarget: true,
    comingSoon: true,
    healthContext: { health: 'yellow', insight: 'Connector retries active for one downstream endpoint.' },
    dashboard: { syncedMinutesAgo: 6, status: 'Partial' },
  },
  {
    key: 'automations',
    label: 'Automations',
    routePath: '/omnidash/automations',
    category: 'automation',
    iconAssetKey: 'automations',
    logoDomain: 'n8n.io',
    chaosTarget: true,
    comingSoon: true,
    healthContext: { health: 'green', insight: 'Automation schedules executing on configured cadence.' },
    dashboard: { syncedMinutesAgo: 3, status: 'Live' },
  },
  {
    key: 'workflows',
    label: 'Workflows',
    routePath: '/omnidash/workflows',
    category: 'automation',
    iconAssetKey: 'workflows',
    logoDomain: 'airflow.apache.org',
    chaosTarget: true,
    comingSoon: true,
    healthContext: { health: 'green', insight: 'Workflow graph validation passes pre-execution gates.' },
    dashboard: { syncedMinutesAgo: 3, status: 'Live' },
  },
  {
    key: 'files',
    label: 'Files',
    routePath: '/omnidash/files',
    category: 'operations',
    iconAssetKey: 'files',
    logoDomain: 'dropbox.com',
    chaosTarget: false,
    comingSoon: true,
    healthContext: { health: 'green', insight: 'Document sync jobs are processing without drift.' },
    dashboard: { syncedMinutesAgo: 7, status: 'Live' },
  },
  {
    key: 'billing',
    label: 'Billing',
    routePath: '/omnidash/billing',
    category: 'operations',
    iconAssetKey: 'billing',
    logoDomain: 'stripe.com',
    chaosTarget: false,
    comingSoon: true,
    healthContext: { health: 'yellow', insight: 'Billing export task retried and recovered automatically.' },
    dashboard: { syncedMinutesAgo: 8, status: 'Partial' },
  },
  {
    key: 'settings',
    label: 'Settings',
    routePath: '/omnidash/settings',
    category: 'control-plane',
    iconAssetKey: 'settings',
    logoDomain: 'okta.com',
    chaosTarget: false,
    comingSoon: true,
    healthContext: { health: 'green', insight: 'Configuration revisions persisted and versioned safely.' },
    dashboard: { syncedMinutesAgo: 2, status: 'Live' },
  },
] as const;

export const APP_REGISTRY: readonly AppRegistryEntry[] = appRegistryEntrySchema.array().parse(appRegistrySource);

if (APP_REGISTRY.length !== 14) {
  throw new Error(`APP_REGISTRY must contain exactly 14 entries. Found: ${APP_REGISTRY.length}`);
}
