> **Historical Note:** This document contains legacy certification terminology. It has been superseded by the manual owner-approval process. CI now produces factual validation summaries only. CI validates. Owner certifies.

/**
 * Feature Truth Ledger — Brain + Senses claims.
 *
 * One slice of the ledger. Composed into the full `featureTruthLedger` by
 * `content/featureTruth.ts`. Every claim cites repo-relative, verifiable
 * evidence; do not add a claim without an evidence path.
 */

import type { FeatureClaim } from './types';

export const brainSensesClaims: readonly FeatureClaim[] = [
  // ───────────────────────── BRAIN ─────────────────────────
  {
    id: 'brain.temporal',
    label: 'Temporal.io durable execution engine',
    category: 'brain',
    status: 'BACKEND_FOUNDATION_ONLY',
    publicCopy: 'Temporal.io durable execution engine',
    releaseCopy: null,
    evidence: [
      'package.json (@temporalio/client,worker,workflow,activity)',
      'orchestrator/requirements.txt (temporalio>=1.22.0)',
      'orchestrator/pyproject.toml',
    ],
    uiRoutes: [],
    apiRoutes: ['orchestrator/server.py'],
    dataStores: [],
    tests: [],
    ownerValidationRequired: false,
    notes:
      'Temporal SDK present in both JS and Python runtimes. A running worker + named workflow reachability was not proven in this audit, so it ships as substrate, not a headline capability.',
  },
  {
    id: 'brain.saga',
    label: 'Saga-style compensation & rollbacks',
    category: 'brain',
    status: 'CERTIFIED_FUNCTIONING',
    publicCopy: 'Saga-style compensation & rollbacks',
    releaseCopy: 'Saga-style compensation and rollback paths',
    evidence: [
      'src/core/orchestrator/ApexOrchestrator.ts',
      'src/core/orchestrator/ChronosLock.ts (rollbackAsync)',
    ],
    uiRoutes: [],
    apiRoutes: [],
    dataStores: [],
    tests: ['tests/'],
    ownerValidationRequired: false,
    notes: 'Idempotency-keyed commit/rollback implemented in ChronosLock.',
  },
  {
    id: 'brain.fastapi',
    label: 'FastAPI / Python AI agent logic',
    category: 'brain',
    status: 'CERTIFIED_FUNCTIONING',
    publicCopy: 'FastAPI / Python AI agent logic',
    releaseCopy: 'FastAPI / Python agent runtime',
    evidence: [
      'orchestrator/server.py',
      'orchestrator/tests/test_final_verification.py',
    ],
    uiRoutes: [],
    apiRoutes: ['orchestrator/server.py'],
    dataStores: [],
    tests: ['orchestrator/tests/'],
    ownerValidationRequired: false,
    notes: 'FastAPI service with pytest coverage in orchestrator package.',
  },
  {
    id: 'brain.pgvector',
    label: 'pgvector semantic memory (RAG)',
    category: 'brain',
    status: 'CERTIFIED_FUNCTIONING',
    publicCopy: 'pgvector semantic memory (RAG)',
    releaseCopy: 'pgvector semantic memory (RAG)',
    evidence: [
      'supabase/migrations/20260303000000_create_memories_table.sql (vector ext + HNSW)',
      'src/lib/memory/MemoryClient.ts',
    ],
    uiRoutes: [],
    apiRoutes: ['src/lib/memory/MemoryClient.ts'],
    dataStores: ['memories'],
    tests: [],
    ownerValidationRequired: false,
    notes: 'pgvector extension + HNSW index migration; client wired.',
  },
  {
    id: 'brain.workflowViz',
    label: 'Workflow state visualization (:8080)',
    category: 'brain',
    status: 'HIDDEN_FOR_RELEASE',
    publicCopy: 'Workflow state visualization (:8080)',
    releaseCopy: null,
    evidence: [],
    uiRoutes: [],
    apiRoutes: [],
    dataStores: [],
    tests: [],
    ownerValidationRequired: false,
    notes:
      'No reachable :8080 workflow UI proven in-repo. Port claim removed from production.',
  },

  // ───────────────────────── SENSES ─────────────────────────
  {
    id: 'senses.ears',
    label: 'Ears: Real-time audio stream perception',
    category: 'senses',
    status: 'BACKEND_FOUNDATION_ONLY',
    publicCopy: 'Ears: Real-time audio stream perception',
    releaseCopy: null,
    evidence: [
      'src/utils/RealtimeAudio.ts',
      'src/omniconnect/ingress/omniport-voice.ts',
      'apps/omnihub-site/dashboard/components/DashboardOverview/hooks/useAgentRecording.ts',
    ],
    uiRoutes: [],
    apiRoutes: [],
    dataStores: [],
    tests: [],
    ownerValidationRequired: false,
    notes:
      'Voice ingress + governed transcript handling exist. A complete, tested mic capture → transcription → response path was not certified, so not shown as a shipped capability.',
  },
  {
    id: 'senses.eyes',
    label: 'Eyes: Multimodal vision input analysis',
    category: 'senses',
    status: 'REQUIRES_OWNER_VALIDATION',
    publicCopy: 'Eyes: Multimodal vision input analysis',
    releaseCopy: null,
    evidence: [
      'src/lib/eyes-vision.ts (validation + Anthropic content-block builder)',
      'apps/omnihub-site/src/components/byom/EyesVisionInput.tsx (image attach UI)',
      'apps/omnihub-site/src/pages/EyesVision.tsx',
      'supabase/functions/byom-proxy/index.ts (backward-compatible multimodal content)',
      'tests/release/eyes-vision-surface.spec.ts',
    ],
    uiRoutes: ['/eyes'],
    apiRoutes: ['supabase/functions/byom-proxy'],
    dataStores: [],
    tests: ['tests/release/eyes-vision-surface.spec.ts'],
    ownerValidationRequired: true,
    notes:
      'UI endpoint /eyes (image-attach + preview, no bytes logged) is wired to the existing byom-proxy as Anthropic-native multimodal content. BYOM provider leg verified (Groq text path returns 200). NOT yet certified: vision requires an Anthropic key entered via the Connect AI cockpit, and edge changes were not Deno-compiled here. Owner runs live vision validation. Live camera capture intentionally omitted.',
  },
  {
    id: 'senses.touch',
    label: 'Touch: Native sensor permission gates',
    category: 'senses',
    status: 'BACKEND_FOUNDATION_ONLY',
    publicCopy: 'Touch: Native sensor permission gates',
    releaseCopy: null,
    evidence: ['capacitor.config.ts', 'supabase/migrations/20260125130000_push_device_tokens.sql'],
    uiRoutes: [],
    apiRoutes: [],
    dataStores: ['push_device_tokens'],
    tests: [],
    ownerValidationRequired: true,
    notes: 'Capacitor native shell present; sensor permission gating not device-validated.',
  },
  {
    id: 'senses.whisper',
    label: 'Whisper local fallback (air-gapped ready)',
    category: 'senses',
    status: 'HIDDEN_FOR_RELEASE',
    publicCopy: 'Whisper local fallback (air-gapped ready)',
    releaseCopy: null,
    evidence: [],
    uiRoutes: [],
    apiRoutes: [],
    dataStores: [],
    tests: [],
    ownerValidationRequired: false,
    notes: 'No local/offline Whisper path found. Removed from production.',
  },
  {
    id: 'senses.capacitor',
    label: 'Capacitor 6.0 native iOS/Android bridges',
    category: 'senses',
    status: 'REQUIRES_OWNER_VALIDATION',
    publicCopy: 'Capacitor 6.0 native iOS/Android bridges',
    releaseCopy: null,
    evidence: ['capacitor.config.ts', 'package.json (@capacitor/core ^6.2.1)', 'android/', 'ios/'],
    uiRoutes: [],
    apiRoutes: [],
    dataStores: [],
    tests: [],
    ownerValidationRequired: true,
    notes: 'Capacitor 6.2.1 shell + android/ios projects present; not validated on a real device.',
  },
] as const;
