/**
 * Feature Truth Ledger — Identity + Conscience claims.
 *
 * One slice of the ledger. Composed into the full `featureTruthLedger` by
 * `content/featureTruth.ts`. Every claim cites repo-relative, verifiable
 * evidence; do not add a claim without an evidence path.
 */

import type { FeatureClaim } from './types';

export const identityConscienceClaims: readonly FeatureClaim[] = [
  // ───────────────────────── IDENTITY ─────────────────────────
  {
    id: 'identity.enclave',
    label: 'Biometric hardware enclave signing',
    category: 'identity',
    status: 'BACKEND_FOUNDATION_ONLY',
    publicCopy: 'Biometric hardware enclave signing',
    releaseCopy: null,
    evidence: ['src/lib/biometric-auth.ts', 'orchestrator/security/request_signing.py'],
    uiRoutes: [],
    apiRoutes: [],
    dataStores: [],
    tests: ['tests/lib/biometric-auth.extended.test.ts'],
    ownerValidationRequired: true,
    notes:
      'WebAuthn implementation present. Hardware-enclave signing of execution receipts is not proven without real-device validation.',
  },
  {
    id: 'identity.deviceRegistry',
    label: 'Zero-Trust Device Registry (Hardware ID)',
    category: 'identity',
    status: 'CERTIFIED_FUNCTIONING',
    publicCopy: 'Zero-Trust Device Registry (Hardware ID)',
    releaseCopy: 'Zero-Trust Device Registry',
    evidence: [
      'src/zero-trust/deviceRegistry.ts',
      'supabase/migrations/20251218000001_create_device_registry_table.sql',
      'tests/zero-trust/baseline.test.ts',
    ],
    uiRoutes: [],
    apiRoutes: ['src/zero-trust/deviceRegistry.ts'],
    dataStores: ['device_registry'],
    tests: ['tests/zero-trust/baseline.test.ts'],
    ownerValidationRequired: false,
    notes: 'Device registry table + integrity logic + baseline tests in-repo.',
  },
  {
    id: 'identity.faceid',
    label: 'FaceID / TouchID execution gating',
    category: 'identity',
    status: 'REQUIRES_OWNER_VALIDATION',
    publicCopy: 'FaceID / TouchID execution gating',
    releaseCopy: null,
    evidence: ['src/lib/biometric-auth.ts (WebAuthn platform authenticator)'],
    uiRoutes: [],
    apiRoutes: [],
    dataStores: [],
    tests: ['tests/lib/biometric-auth.extended.test.ts'],
    ownerValidationRequired: true,
    notes:
      'WebAuthn platform-authenticator path implemented; FaceID/TouchID execution gating must be validated on a real device before public claim. See identity.webauthn for the server-side flow status.',
  },
  {
    id: 'identity.webauthn',
    label: 'WebAuthn passkey registration & assertion',
    category: 'identity',
    status: 'REQUIRES_OWNER_VALIDATION',
    publicCopy: 'WebAuthn passkey registration & assertion',
    releaseCopy: null,
    evidence: [
      'supabase/functions/identity-webauthn/index.ts (challenge/register/assert + signature verify)',
      'supabase/functions/identity-webauthn/webauthn-core.ts (COSE parse + ES256 ECDSA verify + sign-counter replay)',
      'apps/omnihub-site/src/lib/webauthnClient.ts (ES256-only)',
      'apps/omnihub-site/src/components/identity/PasskeySection.tsx',
      'apps/omnihub-site/src/pages/Login.tsx (/login surface)',
      'tests/release/identity-webauthn-surface.spec.ts (real ES256 round-trip)',
    ],
    uiRoutes: ['/login'],
    apiRoutes: ['supabase/functions/identity-webauthn'],
    dataStores: ['device_registry', 'audit_logs'],
    tests: ['tests/release/identity-webauthn-surface.spec.ts'],
    ownerValidationRequired: true,
    notes:
      'Complete software path: server-side challenge, attestation parse → ES256 public-key extraction, assertion ECDSA/P-256 signature verification against the stored key, and sign-counter replay protection (round-trip unit-tested). Passkey UI exposed at /login. Reuses device_registry + audit_logs (no new table). Edge function must be deployed by the owner; real-device FaceID/TouchID validation remains owner-gated (see identity.faceid). Not auto-certified until the owner validates on a real device.',
  },
  {
    id: 'identity.noBiometricEgress',
    label: 'No biometric data leaves the device',
    category: 'identity',
    status: 'BACKEND_FOUNDATION_ONLY',
    publicCopy: 'No biometric data leaves the device',
    releaseCopy: null,
    evidence: ['src/lib/biometric-auth.ts'],
    uiRoutes: [],
    apiRoutes: [],
    dataStores: [],
    tests: [],
    ownerValidationRequired: true,
    notes:
      'Architectural property of WebAuthn (only public-key material leaves device); paired to FaceID/TouchID owner validation.',
  },
  {
    id: 'identity.hwReceipts',
    label: 'Cryptographic receipts signed by hardware',
    category: 'identity',
    status: 'BACKEND_FOUNDATION_ONLY',
    publicCopy: 'Cryptographic receipts signed by hardware',
    releaseCopy: null,
    evidence: ['orchestrator/security/request_signing.py'],
    uiRoutes: [],
    apiRoutes: [],
    dataStores: [],
    tests: [],
    ownerValidationRequired: true,
    notes: 'Request signing exists; hardware-rooted signing not proven without device validation.',
  },

  // ───────────────────────── CONSCIENCE ─────────────────────────
  {
    id: 'conscience.triforce',
    label: 'Tri-Force: Guardian → Planner → Executor',
    category: 'conscience',
    status: 'CERTIFIED_FUNCTIONING',
    publicCopy: 'Tri-Force: Guardian → Planner → Executor',
    releaseCopy: 'Tri-Force governance: Guardian → Planner → Executor',
    evidence: [
      'src/guardian/loops.ts',
      'src/guardian/heartbeat.ts',
      'orchestrator/security/guardian_fabric.py',
      'package.json script: guardian:status',
    ],
    uiRoutes: [],
    apiRoutes: ['src/lib/apex/control-plane.ts'],
    dataStores: [],
    tests: [],
    ownerValidationRequired: false,
    notes: 'Guardian runtime loops + fabric + status CLI present.',
  },
  {
    id: 'conscience.manmode',
    label: 'MAN Mode (Manual Approval Node) gates',
    category: 'conscience',
    status: 'CERTIFIED_FUNCTIONING',
    publicCopy: 'MAN Mode (Manual Approval Node) gates',
    releaseCopy: 'MAN Mode (Manual Approval Node) gates for high-risk actions',
    evidence: [
      'supabase/migrations/20260108120000_man_mode.sql (man_tasks)',
      'supabase/functions/omnibridge-control/index.ts',
      'supabase/migrations/20260417000000_omnibridge_events.sql (awaiting_man)',
    ],
    uiRoutes: [],
    apiRoutes: ['supabase/functions/omnibridge-control/index.ts'],
    dataStores: ['man_tasks'],
    tests: [],
    ownerValidationRequired: false,
    notes: 'man_tasks table + awaiting-approval enforcement in edge functions.',
  },
  {
    id: 'conscience.humanOversight',
    label: 'Human-oversight policy controls',
    category: 'conscience',
    status: 'CERTIFIED_FUNCTIONING',
    publicCopy: 'Human-oversight policy controls',
    releaseCopy: 'Human-oversight policy controls',
    evidence: ['src/omniconnect/policy/policy-engine.ts'],
    uiRoutes: [],
    apiRoutes: [],
    dataStores: [],
    tests: [],
    ownerValidationRequired: false,
    notes: 'Policy engine enforces oversight rules over agent actions.',
  },
  {
    id: 'conscience.omnilink9876',
    label: 'OmniLink single controlled port (9876)',
    category: 'conscience',
    status: 'HIDDEN_FOR_RELEASE',
    publicCopy: 'OmniLink single controlled port (9876)',
    releaseCopy: null,
    evidence: [],
    uiRoutes: [],
    apiRoutes: ['supabase/functions/omnilink-port/index.ts'],
    dataStores: [],
    tests: [],
    ownerValidationRequired: false,
    notes:
      'OmniLink ingress exists, but the literal "port 9876" is referenced only in marketing copy — no service binds or health-checks 9876. The numeric port claim is removed.',
  },
  {
    id: 'conscience.semanticEvents',
    label: 'Canonical typed semantic event normalization',
    category: 'conscience',
    status: 'CERTIFIED_FUNCTIONING',
    publicCopy: 'Canonical typed semantic event normalization',
    releaseCopy: 'Canonical typed semantic event normalization',
    evidence: [
      'src/omniconnect/types/canonical.ts',
      'supabase/functions/_shared/omniport-normalize.ts',
    ],
    uiRoutes: [],
    apiRoutes: [],
    dataStores: [],
    tests: ['tests/omniconnect/omniport.spec.ts'],
    ownerValidationRequired: false,
    notes: 'Canonical event types + normalization layer with tests.',
  },
] as const;
