> **Historical Note:** This document contains legacy certification terminology. It has been superseded by the manual owner-approval process. CI now produces factual validation summaries only. CI validates. Owner certifies.

/**
 * Feature Truth Ledger — Memory + Immune claims.
 *
 * One slice of the ledger. Composed into the full `featureTruthLedger` by
 * `content/featureTruth.ts`. Every claim cites repo-relative, verifiable
 * evidence; do not add a claim without an evidence path.
 */

import type { FeatureClaim } from './types';

export const memoryImmuneClaims: readonly FeatureClaim[] = [
  // ───────────────────────── MEMORY ─────────────────────────
  {
    id: 'memory.auditLogging',
    label: 'Audit logging mapped to privacy-record workflows',
    category: 'memory',
    status: 'CERTIFIED_FUNCTIONING',
    publicCopy: 'Audit logging mapped to privacy-record workflows',
    releaseCopy: 'Structured audit logging across governed actions',
    evidence: [
      'src/security/auditLog.ts',
      'supabase/functions/apex-agent/index.ts (audit_logs)',
      'apps/omnihub-site/dashboard/utils/exportAuditLog.ts',
    ],
    uiRoutes: [],
    apiRoutes: ['src/security/auditLog.ts'],
    dataStores: ['audit_logs'],
    tests: [],
    ownerValidationRequired: false,
    notes: 'audit_logs write paths across edge functions + export utility.',
  },
  {
    id: 'memory.replay',
    label: 'OmniTrace forensic decision replay',
    category: 'memory',
    status: 'CERTIFIED_FUNCTIONING',
    publicCopy: 'OmniTrace forensic decision replay',
    releaseCopy: 'OmniTrace decision replay over recorded audit events',
    evidence: [
      'apps/omnihub-site/src/components/OmniTracePanel.tsx (RLS-scoped audit_logs query)',
      'apps/omnihub-site/src/lib/omniTrace.ts (ordering/grouping logic)',
      'apps/omnihub-site/src/pages/OmniTrace.tsx',
      'apps/omnihub-site/src/App.tsx (/omni-trace route)',
      'tests/release/omni-trace-surface.spec.ts',
    ],
    uiRoutes: ['/omni-trace'],
    apiRoutes: [],
    dataStores: ['audit_logs'],
    tests: ['tests/release/omni-trace-surface.spec.ts'],
    ownerValidationRequired: false,
    notes:
      'Live /omni-trace surface replays the current user’s real audit_logs (RLS-scoped), reconstructing an ordered decision timeline grouped by correlation id when present. Scoped to recorded-event replay; cross-agent full-chain linking (memory.fullChain) remains separate and uncertified because no correlation id is persisted into audit_logs.metadata today.',
  },
  {
    id: 'memory.fullChain',
    label: 'Full reconstruction of any agent chain',
    category: 'memory',
    status: 'HIDDEN_FOR_RELEASE',
    publicCopy: 'Full reconstruction of any agent chain',
    releaseCopy: null,
    evidence: [],
    uiRoutes: [],
    apiRoutes: [],
    dataStores: [],
    tests: [],
    ownerValidationRequired: false,
    notes: 'Not every agent step is proven to emit trace events. Removed from production.',
  },
  {
    id: 'memory.retention365',
    label: '365-day structured log retention',
    category: 'memory',
    status: 'BACKEND_FOUNDATION_ONLY',
    publicCopy: '365-day structured log retention',
    releaseCopy: null,
    evidence: ['scripts/compliance/generate_retention_evidence.mjs'],
    uiRoutes: [],
    apiRoutes: [],
    dataStores: [],
    tests: [],
    ownerValidationRequired: true,
    notes:
      'Retention evidence generator exists; the specific 365-day numeric guarantee requires a verified scheduled-job/policy in production.',
  },
  {
    id: 'memory.dpiaFria',
    label: 'DPIA / FRIA audit-ready documentation',
    category: 'memory',
    status: 'REQUIRES_OWNER_VALIDATION',
    publicCopy: 'DPIA / FRIA audit-ready documentation',
    releaseCopy: null,
    evidence: [],
    uiRoutes: [],
    apiRoutes: [],
    dataStores: [],
    tests: [],
    ownerValidationRequired: true,
    notes: 'Current DPIA/FRIA documents must be confirmed before public claim.',
  },

  // ───────────────────────── IMMUNE ─────────────────────────
  {
    id: 'immune.armageddon40k',
    label: 'Armageddon L7: 40,000 adversarial iterations',
    category: 'immune',
    status: 'HIDDEN_FOR_RELEASE',
    publicCopy: 'Armageddon L7: 40,000 adversarial iterations',
    releaseCopy: null,
    evidence: [],
    uiRoutes: [],
    apiRoutes: [],
    dataStores: [],
    tests: [],
    ownerValidationRequired: false,
    notes: 'No 40,000-iteration adversarial harness found in-repo. Numeric proof removed.',
  },
  {
    id: 'immune.zeroEscape',
    label: '0% escape rate on goal hijack & tool misuse',
    category: 'immune',
    status: 'HIDDEN_FOR_RELEASE',
    publicCopy: '0% escape rate on goal hijack & tool misuse',
    releaseCopy: null,
    evidence: [],
    uiRoutes: [],
    apiRoutes: [],
    dataStores: [],
    tests: ['tests/prompt-defense/'],
    ownerValidationRequired: false,
    notes:
      'Prompt-defense tests exist but no current evidence substantiates a 0% escape numeric. Claim removed.',
  },
  {
    id: 'immune.omnisentry',
    label: 'OmniSentry self-healing monitor',
    category: 'immune',
    status: 'CERTIFIED_FUNCTIONING',
    publicCopy: 'OmniSentry self-healing monitor',
    releaseCopy: 'OmniSentry self-healing monitor (live status)',
    evidence: [
      'src/lib/omni-sentry.ts (circuit breaker + self-healing recovery)',
      'apps/omnihub-site/src/components/OmniSentryPanel.tsx (live surface)',
      'apps/omnihub-site/src/pages/OmniSentry.tsx',
      'apps/omnihub-site/src/App.tsx (/omni-sentry route)',
      'src/main.tsx (startup activation from preference)',
      'tests/release/omni-sentry-surface.spec.ts',
    ],
    uiRoutes: ['/omni-sentry'],
    apiRoutes: [],
    dataStores: [],
    tests: ['tests/release/omni-sentry-surface.spec.ts'],
    ownerValidationRequired: false,
    notes:
      'Self-healing monitor lib is now surfaced live at /omni-sentry via OmniSentryPanel, which drives the real initializeOmniSentry/getHealthStatus runtime and persists activation across reloads (main.tsx startup initializer).',
  },
  {
    id: 'immune.secretScanning',
    label: 'Gitleaks + TruffleHog secret scanning',
    category: 'immune',
    status: 'CERTIFIED_FUNCTIONING',
    publicCopy: 'Gitleaks + TruffleHog secret scanning',
    releaseCopy: 'Gitleaks + TruffleHog secret scanning in CI',
    evidence: [
      '.github/gitleaks.toml',
      '.github/workflows/secret-scanning.yml',
      '.github/workflows/production-readiness.yml (trufflesecurity/trufflehog pinned)',
    ],
    uiRoutes: [],
    apiRoutes: [],
    dataStores: [],
    tests: ['.github/workflows/secret-scanning.yml'],
    ownerValidationRequired: false,
    notes: 'Both tools are pinned and invoked in CI workflows.',
  },
  {
    id: 'immune.omega',
    label: 'OMEGA infrastructure hardening layer',
    category: 'immune',
    status: 'CERTIFIED_FUNCTIONING',
    publicCopy: 'OMEGA infrastructure hardening layer',
    releaseCopy: 'OMEGA infrastructure hardening layer',
    evidence: ['omega/', 'scripts/omega/cli.ts', '.github/workflows/ci-runtime-gates.yml'],
    uiRoutes: [],
    apiRoutes: [],
    dataStores: [],
    tests: ['omega/test_omega.sh'],
    ownerValidationRequired: false,
    notes: 'OMEGA module + CLI + CI runtime-gate integration.',
  },
] as const;
